CREATE SEQUENCE REPLY_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

DROP SEQUENCE REPLY_SEQ;

CREATE TABLE BOARD_REPLY(
	REPLY_NUM NUMBER(8),
	BOARD_NUM NUMBER(5),
	MEMBER_ID VARCHAR2(40),
	REPLY_CONTENTS VARCHAR2(4000),
	CONSTRAINT REPLY_PK PRIMARY KEY(REPLY_NUM),
	CONSTRAINT REPLY_NUM_FK FOREIGN KEY(BOARD_NUM) 
	REFERENCES BOARD(BOARD_NUM),
	CONSTRAINT REPLY_MEMBER_FK FOREIGN KEY(MEMBER_ID) 
	REFERENCES TBL_MEMBER(MEMBER_ID)
);

SELECT * FROM BOARD_REPLY;



SELECT * FROM BOARD_REPLY WHERE BOARD_NUM = 114 ORDER BY REPLY_NUM DESC;



